config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :ratings
  resources :people
  resources :projects
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :person

  validates :score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }

  def promoter?
    score >= 9 && score <= 10
  end

  def passive?
    score >= 7 && score <= 8
  end

  def detractor?
    score <= 6 && score >= 0
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[ show edit update destroy ]

  # GET /ratings or /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to rating_url(@rating), notice: "Rating was successfully created." }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to rating_url(@rating), notice: "Rating was successfully updated." }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url, notice: "Rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.require(:rating).permit(:person_id, :score)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: rating) do |form| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :person_id, class: 'form-label' %>
      <%= form.text_field :person_id, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :score, class: 'form-label' %>
      <%= form.number_field :score, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <% if rating.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', rating, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if rating.persisted? %>
      <%= link_to "Cancel", rating, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", ratings_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Edit Rating</h1>

<%= render 'form', rating: @rating %>

app/views/ratings/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Ratings</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_rating_path, class: 'btn btn-primary' do %>
    Add New Rating
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Person</th>
            <th>Score</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @ratings.each do |rating| %>
        <%= content_tag :tr, id: dom_id(rating), class: dom_class(rating) do %>
          

                      <td><%= rating.person %></td>
                      <td><%= rating.score %></td>
          
          
            <td><%= link_to 'Show', rating %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form', rating: @rating %>

app/views/ratings/show.html.erb
<div class="page-header">
  <%= link_to ratings_path, class: 'btn btn-default' do %>
    All Ratings
  <% end %>
  <%= link_to edit_rating_path(@rating), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show rating</h1>
</div>

<dl class="dl-horizontal">
  <dt>Person:</dt>
  <dd><%= @rating.person %></dd>
  <dt>Score:</dt>
  <dd><%= @rating.score %></dd>
</dl>